# Generated by Django 5.1.1 on 2024-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Pop', 'Pop Music'), ('Jazz', 'Jazz Music'), ('R&B', 'R&B Music'), ('Rock', 'Rock Music'), ('Country', 'Country Music'), ('Dance', 'Dance Music'), ('Hip Hop', 'Hip Hop Music'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_URL', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
