# Generated by Django 5.1.1 on 2024-09-05 17:14

import django.core.validators
import my_plants_app.plants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Outdoor', 'Outdoor Plants'), ('Indoor', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(2), my_plants_app.plants.validators.validate_name_contains_only_letters])),
                ('image_URL', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
