# Generated by Django 5.1.1 on 2024-09-05 16:59

import django.core.validators
import my_plants_app.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plants_app.accounts.validators.validate_first_letter_capital])),
                ('last_name', models.CharField(max_length=20, validators=[my_plants_app.accounts.validators.validate_first_letter_capital])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
