# Generated by Django 5.1 on 2024-08-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_create_like_and_comment_models'),
        ('photos', '0002_alter_photo_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentYoPhoto',
            new_name='PhotoComment',
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
        ),
        migrations.DeleteModel(
            name='LikePhoto',
        ),
    ]
