# Generated by Django 5.1.1 on 2024-09-04 16:26

import django.core.validators
import fruitipedia.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.accounts.validators.name_validate_starts_with_letter])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), fruitipedia.accounts.validators.name_validate_starts_with_letter])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
