# Generated by Django 5.1.1 on 2024-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
