[
  { "Employee ": "Poole, Tracy", "Benefits ": "R" },
  { "Employee ": "Ramos, Jan", "Benefits ": "DMR" },
  { "Employee ": "Jennings, Gary", "Benefits ": "DM" },
  { "Employee ": "Ortega, Jeffrey", "Benefits ": "" },
  { "Employee ": "Shields, Robert", "Benefits ": "" },
  { "Employee ": "Gregory, Jon", "Benefits ": "R" },
  { "Employee ": "Sheppard, Curtis", "Benefits ": "D" },
  { "Employee ": "Williamson, Sumed", "Benefits ": "" },
  { "Employee ": "Moreno, Chris", "Benefits ": "R" },
  { "Employee ": "Munoz, Michael", "Benefits ": "DMR" },
  { "Employee ": "Kirby, Michael", "Benefits ": "R" },
  { "Employee ": "Jenkins, Scott", "Benefits ": "DMR" },
  { "Employee ": "Ross, Janice", "Benefits ": "R" },
  { "Employee ": "Kelley, Nancy", "Benefits ": "" },
  { "Employee ": "Blackwell, Brandon", "Benefits ": "" },
  { "Employee ": "Bowers, Tammy", "Benefits ": "DMR" },
  { "Employee ": "Fleming, Irv", "Benefits ": "DMR" },
  { "Employee ": "Skinner, Jason", "Benefits ": "R" },
  { "Employee ": "Wade, Kevin", "Benefits ": "DMR" },
  { "Employee ": "Barrett, John", "Benefits ": "R" },
];
