# Generated by Django 5.1 on 2024-09-02 09:26

import petstagram_2.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/', validators=[petstagram_2.photos.validators.file_size_validator]),
        ),
    ]
