# Generated by Django 5.1 on 2024-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_create_pet_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
